export const TODO__TODO_REQUEST = 'TODO__TODO_REQUEST';
export const TODO__TODO_RESPONSE_OK = 'TODO__TODO_RESPONSE_OK';
export const TODO__TODO_RESPONSE_NOK = 'TODO__TODO_RESPONSE_NOK'

export const TODO__TODOS_REQUEST = 'TODO__TODOS_REQUEST';
export const TODO__TODOS_RESPONSE_OK = 'TODO__TODOS_RESPONSE_OK';
export const TODO__TODOS_RESPONSE_NOK = 'TODO__TODOS_RESPONSE_NOK';