export const USER__USER_REQUEST = 'USER__USER_REQUEST';
export const USER__USER_RESPONSE_OK = 'USER__USER_RESPONSE_OK';
export const USER__USER_RESPONSE_NOK = 'USER__USER_RESPONSE_NOK'

export const USER__USERS_REQUEST = 'USER__USERS_REQUEST';
export const USER__USERS_RESPONSE_OK = 'USER__USERS_RESPONSE_OK';
export const USER__USERS_RESPONSE_NOK = 'USER__USERS_RESPONSE_NOK';